services:
  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mysql-escapeH
    ports:
      - 1541:3306
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d/
      - MYSQL_DATA:/var/lib/mysql
    restart: always
    healthcheck: # MySQL 준비 여부 확인
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  spring_jar:
    build:
      context: ./project
    container_name: jar-escapeH
    depends_on:
      mysql:
        condition: service_healthy  # healthcheck 통과 후 시작
    ports:
      - 2024:2024
    restart: always

volumes:
  MYSQL_DATA:
